### ISSUE TITLE
FM to XML, backslashes are not escaped

### ISSUE THREAD

**Issue by jwillinghalpern** [DanShockley/FmClipTools#3]
Backslashes are not escaped completely when converting from fm objects to xml:
Here are some examples of how backslashes are halved with every iteration of converting to xml and then back to FM:

![screen shot 2019-01-05 at 2 53 59 pm](https://user-images.githubusercontent.com/16845102/50730081-c33d8200-10f9-11e9-9338-e4c1f71bef30.png)

**Comment by jwillinghalpern** [comment]
I sent a pull request that gracefully solves this issue. It was a problem with setting a var from a shell script echo in prettifyXML.

**Comment by DanShockley** [comment]
Thanks for the pull request. That seems to fix this well.
