### ISSUE TITLE
Add support for Value Lists

### ISSUE THREAD

**Issue by quarfie** [DanShockley/FmClipTools#6]
To make it work with value lists, add after line 98 in fmObjectTranslator.applescript...

```
, ¬
			{objName:"ValueList", objCode:"XMVL"}
```

**Comment by DanShockley** [comment]
Sorry about the delay. This has been added, bringing fmObjectTranslator to version 4.0.8. 
I don't currently have FileMaker 18 active on my Mac - can you test it and report back?

**Comment by DanShockley** [comment]
Nevermind - I forgot this was in FileMaker 17. I tested it, and the new code works.
