### ISSUE TITLE
not working in FM 18 and Catalina...??

### ISSUE THREAD

**Issue by LinuxPad** [DanShockley/FmClipTools#8]
I can't seem to get this working in OS X Catalina and FM 18..   Any advice or do you have it working???

**Comment by cristoslc** [comment]
@LinuxPad Did you solve this? I haven't had issues in FM19 on Catalina, but haven't tested in 18.

**Comment by DanShockley** [comment]
@LinuxPad - if it is still not working, can you give more info about what happens? 
For example, can you list: 
1) Here's what I did. 
2) Here's what I expected to happen. 
3) Here's what happened instead.

**Comment by DanShockley** [comment]
With no further info, I'm closing this Issue.
